# Generated by Django 4.1.7 on 2023-03-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'клиент',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'продукт',
            },
        ),
        migrations.CreateModel(
            name='StockRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('limit', models.PositiveIntegerField(verbose_name='общий лимит')),
            ],
            options={
                'verbose_name': 'склад',
            },
        ),
        migrations.CreateModel(
            name='StockRoomBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(verbose_name='лимит')),
                ('tariff', models.DecimalField(decimal_places=1, help_text='за единицу продукта', max_digits=10, verbose_name='тариф')),
            ],
            options={
                'verbose_name': 'позиция на складе',
            },
        ),
        migrations.CreateModel(
            name='StockRoomBasketPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='количество')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_room_basket_position', to='stockroom.client', verbose_name='владелец')),
                ('stock_room_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_room_basket_position', to='stockroom.stockroombasket', verbose_name='позиция на складе')),
            ],
            options={
                'verbose_name': 'продукт на складе',
            },
        ),
        migrations.AddField(
            model_name='stockroombasket',
            name='clients',
            field=models.ManyToManyField(related_name='stock_room_baskets', through='stockroom.StockRoomBasketPosition', to='stockroom.client', verbose_name='клиенты'),
        ),
        migrations.AddField(
            model_name='stockroombasket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_room_baskets', to='stockroom.product', verbose_name='продукт'),
        ),
        migrations.AddField(
            model_name='stockroombasket',
            name='stock_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_room_baskets', to='stockroom.stockroom', verbose_name='склад'),
        ),
        migrations.AddField(
            model_name='stockroom',
            name='products',
            field=models.ManyToManyField(related_name='stock_rooms', through='stockroom.StockRoomBasket', to='stockroom.product', verbose_name='продукт'),
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(verbose_name='дистанция')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='stockroom.client', verbose_name='клиент')),
                ('stock_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='stockroom.stockroom', verbose_name='склад')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='количество')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_products', to='stockroom.client', verbose_name='владелец')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_products', to='stockroom.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукт клиента',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(related_name='clients', through='stockroom.ClientProduct', to='stockroom.product', verbose_name='продукты'),
        ),
    ]
